yanaagi/cs-expo-2023

cs-expo-2023/app/events/cs-expo/index.tsx, cs-expo-2023/app/events/dev-day/index.tsx
Edited back-end for cs-expo and dev-day skeleton.
=> Jj backend

README.md
In progress README. Only covered git **pull requests**.
=> docs: WRITE early version of README

cs-expo-2023/components/Footer.tsx
- made the footer relative, not fixed
=> FIX the Footer component

cs-expo-2023/app/projects/page.tsx, cs-expo-2023/components/PartnersHeader.tsx, cs-expo-2023/components/ThesisPosterCard.tsx
It's not finished yet; it still needs to be adjusted in the PartnersHeader and ThesisPosterCard. There is still a lack of responsiveness in the Partners section and in the Thesis, specifically with the three borders that have categories and for each Thesis Project."
=> feat: ADD the component PartnersHeader.tsx and ThesisPosterCard.tsx

cs-expo-2023/components/PartnersHeader.tsx
=> fix: UPDATE the PartnersHeader.tsx

README.md
Add Table of Contents for readme
=> docs: ADD a Table of Contents for README file

cs-expo-2023/app/events/dev-day/page.tsx
feat: add speaker panel, photo panel, and speaker's profession and description.
=> feat: add speaker panel, photo panel, and speaker's profession and description.

cs-expo-2023/components/NavBar.tsx
- changed the transparent dropdown of defaultMenu to white background
=> fix: UPDATE NavBar.tsx

cs-expo-2023/components/Footer.tsx
Fixed cs expo logo not loading
=> fix: MODIFY footer component to load logo

README.md
fixed links of the table
added a file tree and folder overview
=> docs:FIX table of contents. ADD a file tree.

cs-expo-2023/components/HallOfFameCarousel.tsx
=> Adjust the left button's position

cs-expo-2023/app/events/page.tsx, cs-expo-2023/components/EventsOverviewHeader.tsx
Regarding the responsiveness of the circular buttons, specifically the growing and shrinking, I haven't been able to figure it out yet so it will be for follow-up for now and I am asking for help on it.
=> feat: ADD 4 circular buttons with working view event detail links

cs-expo-2023/app/projects/page.tsx, cs-expo-2023/components/ProjectsCarousel.tsx, cs-expo-2023/components/ProjectsHeader.tsx
fixes:
- smoothen the transition between the last (NLP) and first (Data Analytics) slides in the carousel
- added mobile responsiveness for the carousel on small screens
- hides the left and right arrows of the carousel on small screens to declutter; the carousel is swipeable
=> fix: smooth transition of carousel & responsiveness - Projects Overview

README.md
fix structure descriptions
remove folder overview
=> docs: FIX project structure

cs-expo-2023/components/Footer.tsx, cs-expo-2023/tailwind.config.ts
=> fix: footer.tsx

cs-expo-2023/app/partners/page.tsx
=> fix: UPDATE responsiveness for partners page

cs-expo-2023/components/Footer.tsx
Change to hover color coral pink
=> REFACTOR: Footer.tsx

cs-expo-2023/app/not-found.tsx, cs-expo-2023/app/progress/page.tsx
Hello ma'am / sir. I would like to request these additional features for error custom page and under development page:
**1. Work in progress**
https://www.loom.com/share/4b036b64cb3e4833a399b38abdeafcc8?sid=b2897c0f-cf3b-4f30-9d58-04f0fc734457
**2. Custom error 404**
https://www.loom.com/share/dcc52164413a46828e4d46361ac4fc36?sid=b2ad6e86-74bd-4072-867d-9018c5db138c
=> feat: ADD custom error not found and under development page.

cs-expo-2023/components/NavBar.tsx
=> REFACTOR: NavBar.tsx

cs-expo-2023/components/NavBar.tsx, cs-expo-2023/thesis-projects.json
=> fix: Work in Progress

cs-expo-2023/app/events/page.tsx, cs-expo-2023/components/EventsOverviewHeader.tsx
- FIXED some line of codes were reverted back at some point due to recent merging issues
=> feat: FIX description responsiveness

cs-expo-2023/app/page.tsx, cs-expo-2023/components/HomeOverviewHeader.tsx
=> fix: MODIFY and ADD @djhbas source code for home page
